### ISSUE TITLE
MqttPlugin recreates MqttClient in loop

### ISSUE THREAD

**Issue by kiranpradeep** [fr3ts0n/AndrOBD-Plugin#13]
Is this recreation intentional as full TCP connection needs to established always? If not, shall I try a PR moving MqttClient at class level and invoke connect/disconnect inside `onCreate` and `onDestroy` methods of  MqttPlugin.java? Mqtt keepalives at 60 seconds will also be enabled. We will also reconnect on detection connection loss.

**Comment by kiranpradeep** [comment]
Closing this since although everything works well initially for a while, I see that unless I keep the MqttPlugin in foreground, after a while (say 5 mins), then the MqttClient.connect() is throwing MqttException. The service is not getting killed but it is just that MqttClient.connect() starts throwing exception after a while in background. If I bring back MqttPlugin to foreground then MqttClient.connect() starts suceeding. For restrictions on background activities in Android, I prefer HTTP (also having platform libs) which is already tracked at #6 

> 2021-04-01 11:50:43.762 13737-14009/com.fr3ts0n.androbd.plugin.mqtt E/MQTT: Publish
>     MqttException (0) - java.net.SocketTimeoutException: failed to connect to /192.168.1.7 (port 1883) from /192.168.1.101 (port 46028) after 30000ms
>         at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
>         at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
>         at java.lang.Thread.run(Thread.java:919)
>      Caused by: java.net.SocketTimeoutException: failed to connect to /192.168.1.7 (port 1883) from /192.168.1.101 (port 46028) after 30000ms
>         at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
>         at libcore.io.IoBridge.connect(IoBridge.java:135)
>         at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
>         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
>         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
>         at java.net.Socket.connect(Socket.java:621)
>         at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74)
>         at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
>         at java.lang.Thread.run(Thread.java:919) 

I also verified if something is wrong with my device/network by successfully running `telnet 192.168.1.7 1883` in android termux application. My test device runs Android version 10 (Redmi Y3 MIUI 11).
